config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookmarks

  devise_scope :user do
    authenticated :user do
      root 'electives#show', as: :authenticated_root
    end

    unauthenticated do
      root 'bookmarks#initial', as: :unauthenticated_root
    end
  end

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
			bookmarks_path
	end

	def after_sign_up_path_for(resource)
			bookmarks_path
	end

	def sign_out_and_redirect(resource)
  			destroy_user_session_path
	end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  # GET /bookmarks
  # GET /bookmarks.json
  def index
    require 'rinku'
    @bookmarks = current_user.bookmarks
  end

  def initial

  end
  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    require 'rinku'
  end

  # GET /bookmarks/new
  def new
    @bookmark = current_user.bookmarks.build
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :title %>
  </div>
  <div class="field">
    <%= f.input :url %>
  </div>
  <div class="actions col-xs-2">
    <%= f.button :submit,:class => "btn-success" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<br>
<br>
<div class="page-header">
<h3>Edit Bookmark</h3>
</div>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<br>
<br>
<div class="page-header">
<h3>My Bookmarks</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>S.No</th>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% i = 1 %>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= i %>
        <td><%= bookmark.title %></td>
        <td><%=raw Rinku.auto_link(bookmark.url, :all, 'target="_blank"') %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Delete', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% i+=1 %>
    <% end %>
  </tbody>
</table>

<br>

app/views/bookmarks/initial.html.erb
<br>
<br>
<br>
<br>
<div class="jumbotron">
  <h1>This is OnBook</h1>
  <p>Your Personal Bookmarking App.</p>
  <p>Now store all your bookmarks on OnBook!</p>
  <p>Login with your e-mail and access them from anywhere!</p> 
</div>

app/views/bookmarks/new.html.erb
<br>
<br>
<div class="page-header">
<h3>Add a Bookmark! :)</h3>
</div>

<%= render 'form' %>

<div class="btn btn-info btn-default col-xs-1">
<%= link_to 'Back', bookmarks_path %>
</div>

app/views/bookmarks/show.html.erb
<br>
<br>
<div class="page-header">
<h3>Your Bookmark</h3>
</div>


<p id="notice"><%= notice %></p>

<div class="panel panel-default">
<div class="panel-body">
<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Link:</strong>
  <%=raw Rinku.auto_link(@bookmark.url, :all, 'target="_blank"') %>
</p>		
</div>
</div>  
<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>OnBook | Online Bookmarking Application</title>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
  <a class="navbar-brand" href=""><b>OnBook</b></a>
  <% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Sign Out",destroy_user_session_path ,:method => :delete %></li>
    <li><%= link_to 'New Bookmark', new_bookmark_path %></li>
  </ul>
  <% else %>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="/users/sign_up">Sign Up</a></li>
    <li><a href="/users/sign_in">Sign In</a></li>
  </ul>
  <% end %>
  </div>
  </nav>
  <title>OnBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
</div>
<br>
<div class="container">
        <p class="text-muted text-center">&copy <b>Lebowski DEVS 2015</b></p>
</div>
</body>
</html>